// CONFIG
export const IS_LOADING_ADDRESS = "IS_LOADING_ADDRESS";

// LOGIN USER
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_TOKEN_USER = "LOGIN_TOKEN_USER";
export const LOGIN_LOADING = "LOGIN_LOADING";

// LOGIN RESET
export const LOGOUT_USER = "LOGOUT_USER";
export const RESET_LOGIN_USER = "RESET_LOGIN_USER";